#Vorlage für abspeichern von Rezepten

#lachssauce_L = {"Rahm in ml": 250,
#           "Lachs": 150,
#           "Salz": 15,
#           "Pfeffer": 10}
            
#Spaghetti_L = {"Spagetty": 250,
#            "Salz": 20}
    
#Kochbuch = {"Lachssauce": lachssauce_L,
#            "Spaghetti": Spaghetti_L,
#            }

#Speise_L = ["Vorspeise", "Hauptspeise", "Nachspeise"]

#Herkunft_L = ["Japan", "Thailand", "Schweiz", "Italien"]

#Alle Angaben von Zutaten in gramm angeben. wenn flüssig oder sonstige Mengenangabe Bitte schreibt beispielsweise:
    #"Anzahl Salz prisen"
    #"Rahm in ml"
# Wichtig ist, das wenn die angabe nicht gramm ist, ist das der Key in der dictionary aus mehreren Wörter besteht.


Nudeln_L = {"Blattspinat": 100,
            "Rucola": 50,
            "Knoblauch anzahl Zehen": 2,
            "Olivenöl in ml": 100,
            "Parmesan": 60,
            "Mandelkerne": 25,
            "Abgeribene Schale von Zitrone": 1,
            "Salz prisen": 1,
            "Zucker": 2,
            "Spargel": 500,
            "Bandnudeln": 400,
            "Radieschen": 75,
            "Zubereitung 1": "Bandnudeln 10 min kochen und anschliessend warmstellen",
            "Zubereitung 2": "...",
            "Zubereitung 3": "servieren"
            #Noch weitere Zubereitungsschritte wären möglich
            
}

Kuchen_L ={"Rhabarber" : 500,
           "Zucker in EL" : 4,
           "Halbfettquark" : 500,
           "Eier in Stück" : 3,
           "Maisstärke in EL" : 2,
           "Mehl in EL" : 2,
           "Salz prisen": 1,
           "Rahm in dl" : 1.5,
           "Zucker" : 50,
           "Butterflocken" : 30,
           "Zubereitung 1": "Rhabarber mit Zucker mischen.",
           "Zubereitung 2": "Ofen auf 200°C Ober-/Unterhitze vorheizen (Heissluft 180°C).",
           "Zubereitung 3": "Quarkmasse: Halbfettquark, Eier, Mehl, Salz, Rahm und Zucker gut verrühren.",
           "Zubereitung 4": "Butterflocken daraufverteilen.",
           "Zubereitung 5": "In der Mitte des vorgeheizten Ofens 35-40 Minuten backen. Herausnehmen, mit Puderzucker bestäuben. Heiss servieren."
}

Parmigiana_L={"Auberginen in Stück": 4,
              "Olivenöl in dl": 0.5,
              "Olivenöl in EL": 0.5,
              "Knoblauch Anzahl Zehen": 2,
              "Gehackte Tomaten in Anzahl Dosen": 1,
              "Salz in TL": 0.5,
              "Pfeffer Menge": "wenig",
              "Mozarella": 150,
              "Parmesan": 100,
              "Basilikumblätter Menge": "einige",
              "Zubereitung 1": "Backofen auf 220 Grad Heissluft vorheizen.",
              "Zubereitung 2": "Auberginen längs in ca. 5 mm dicke Scheiben schneiden, mit Öl bestreichen, auf zwei mit Backpapier belegte Bleche verteilen.",
              "Zubereitung 3": "Backen: ca. 20 Min. im Ofen.",
              "Zubereitung 4":"Öl in einer Pfanne warm werden lassen. Knoblauch dazupressen, andämpfen. Tomaten beigeben, würzen, aufkochen, Sauce unter gelegentlichem Rühren bei kleiner Hitze ca. 20 Min. köcheln.",
              "Zubereitung 5": "Mozzarella zerzupfen. 3 EL Tomatensauce und die Hälfte der Auberginen in der vorbereiteten Form verteilen. Je die Hälfte von der Tomatensauce, des Mozzarellas und des Parmesans darauf verteilen. Restliche Auberginen, Tomatensauce, restlichen Mozzarella und Parmesan darauf verteilen.",
              "Zubereitung 6": "Fertig backen: ca. 20 Min. Herausnehmen, ca. 5 Min. ruhen lassen.",
              "Zubereitung 7": "Basilikum darüberstreuen."
}

Lasagne_L= {"Rüebli": 200,
            "Selerie": 200,
            "Zwiebeln in Stück": 2,
            "Knoblauch Anzahl Zelehn": 2,
            "Majoran Anzahl Zweiglein": 1,
            "Rosmarin Anzahl Zweiglein": 1,
            "Rindshackfleisch": 600,
            "Tomatenpüree in EL": 4,
            "Rotwein in dl": 3,
            "Fleischbouillon in dl": 4,
            "Butter": 25,
            "Mehl in EL": 3,
            "Milch in dl": 6,
            "Salz in TL": 0.75,
            "Pfeffer Menge": "wenig",
            "Lasagne Anzahl Blätter": 15,
            "Parmesan": 70,
            "Zubereitung 1": "Gemüse schälen. Rüebli und Sellerie in Würfeli schneiden oder grob reiben. Zwiebeln fein hacken, Knoblauch pressen. Majoran und Rosmarin fein schneiden.",
            "Zubereitung 2": "Wenig Öl im Brattopf heiss werden lassen. Fleisch portionenweise je ca. 2 Min. anbraten. Herausnehmen, Hitze reduzieren, Bratfett auftupfen, evtl. wenig Öl beigeben. Zwiebeln und Knoblauch andämpfen, Tomatenpüree kurz mitdämpfen. Rüebli und Sellerie beigeben, kurz weiterdämpfen. Wein und Bouillon dazugiessen, aufkochen, Hitze reduzieren. Majoran und Rosmarin mit dem Fleisch wieder beigeben, mischen, zugedeckt ca. 30 Min. köcheln, würzen.",
            "Zubereitung 3": "Butter in einer Pfanne warm werden lassen. Mehl beigeben, unter Rühren mit dem Schwingbesen dünsten, das Mehl darf dabei keine Farbe annehmen. Pfanne von der Platte nehmen. Milch dazugiessen, unter Rühren aufkochen, Hitze reduzieren, würzen, bei mittlerer Hitze unter gelegentlichem Rühren ca. 10 Min. köcheln, bis die Sauce sämig ist.",
            "Zubereitung 4": "Ofen auf 200 Grad vorheizen. 4 EL Béchamelsauce in der vorbereiteten Form verteilen. Lasagne-Blätter, Fleisch- und Béchamelsauce lagenweise in die Form schichten, mit Béchamelsauce abschliessen. Käse darüberstreuen.",
            "Zubereitung 5": "Backen: ca. 35 Min. in der unteren Hälfte des Ofens. Herausnehmen, ca. 5 Min. ruhen lassen, Lasagne anrichten."   
}

Bruschetta_L= {"Tomaten in Stück": 10,
               "Zwiebeln in Stück": 1,
               "Knoblauch Anzahl Zehen": 1,
               "Baguettes oder Ciabatta": 1,
               "Parmesan Menge": "etwas",
               "Basilikum Bund": 1,
               "Olivenöl Menge": "etwas",
               "Oregano Menge": "etwas",
               "Balsamico in ml": 50,
               "Rotweil in ml": 50,
               "Orangensaft in ml": 50,
               "Honig in EL": 2,
               "Salz und Pfeffer": "Nach Bedarf",
               "Pimentpulfer in Prisen": 1,
               "Zubereitung 1": "Entfernen Sie zuerst das Grünzeug der Tomaten gründlich und schneiden Sie sie leicht ein. Geben Sie die bearbeiteten Tomaten in einen Topf mit heißem Salzwasser (ggf. mit etwas Öl). Lassen Sie die Tomaten solange in diesem Wasser, bis sich die Haut an den Schnittstellen löst. Nehmen Sie die Tomaten nun aus dem Topf und lassen Sie diese abkühlen. Daraufhin entfernen Sie die Schalen der Tomaten, welche sich durch das Erhitzen vom Fruchtfleisch gelöst haben.",
               "Zubereitung 2": "Nun werden die Tomaten halbiert und die Kerne und das weiche Fruchfleisch beseitigt. Daraufhin schneiden Sie die Tomaten in kleine Stückchen und geben diese in einen Sieb zum Abtropfen. Leisten Sie etwas Nachhilfe, indem Sie leicht auf die Tomatenstücke eindrücken. Haben die Tomaten nun die richtige Konsistenz erreicht (nicht zu wässrig), geben Sie diese mit dem klein gehackten Basilikum, der Zwiebel und dem Knoblauch in eine Schüssel. Nun ist der aufwendigste Teil geschafft.",
               "Zubereitung 3": "Übergießen Sie die Masse nun mit einem Schuss Olivenöl und geben Sie wahlweise die Gewürze hinzu. Nachdem Sie die Tomaten ein weiteres Mal vorsichtig verrührt haben, können Sie die Balsamicocreme zubereiten. Hierzu bringen sie unter ständigem rühren Balsamico und Rotwein zum Kochen. Sobald die Masse dickflüssig ist, fügen Sie den Orangensaft und den Honig hinzu. Lassen Sie das ganze nochmals aufkochen, bis es dickflüssig ist und stellen Sie es zum Abkühlen zur Seite.",
               "Zubereitung 4": "Schneiden Sie nun das Baguette in 2 cm dicke Scheiben und braten Sie diese in einer Pfanne mit heißem Olivenöl auf beiden Seiten an, bis sie goldbraun sind. Jetzt sollten Sie schnell die Tomatenmasse mit einem Esslöffel auf die Brötchenteile geben, da sie sonst kalt und matschig werden. Breiten Sie die kleinen Bruschette auf einem Teller aus und verteilen Sie sie etwas. Nun Balsamicocreme auf ihnen verteilen. Zum Schluss geben Sie noch etwas geriebenen Parmesan über die Teilchen und garnieren Sie diese ggf. mit einem kleinen Basilikumblättchen. Bis das geschafft ist, haben die Bruschette die richtige Temperatur zum Verzehr erreicht."
}

Panna_cotta_L = {"Gelatine Anzahl Blätter": 2,
                 "Vollrahm in dl": 4,
                 "Milch in dl": 1,
                 "Zucker in EL": 2.5,
                 "Vanillestängel Anzahl": 1,
                 "Zubereitung 1": "Gelatine ca. 5 Min. in kaltes Wasser einlegen. Rahm, Milch und Zucker in eine Pfanne geben. Vanillestängel längs aufschneiden, Samen auskratzen, beides beigeben, mit dem Schwingbesen unter Rühren aufkochen. Hitze reduzieren, auf ca. 4 dl einkochen. Pfanne von der Platte nehmen. Gelatine abtropfen, gut unter die heisse Flüssigkeit rühren. Masse durch ein Sieb in einen Messbecher giessen, in die vorbereiteten Förmchen giessen, auskühlen. Zugedeckt im Kühlschrank ca. 4 Std. fest werden lassen.",
                 "Zubereitung 2": "Panna cotta mit einer Messerspitze sorgfältig vom Förmchenrand lösen. Förmchen kurz in heisses Wasser tauchen, Panna cotta auf Teller stürzen."

}

Panforte_L = {"Mandeln": 200,
              "Mehl": 100,
              "Orangeat": 100,
              "Sultaninen": 100,
              "Lebkuchengewürz in TL": 0.5,
              "Zimt in TL": 0.5,
              "Muskat in Msp.": 1,
              "Salz Prisen": 1,
              "Dunkelschokolade": 100,
              "Flüssighonig": 200,
              "Rahm in EL": 2,
              "Puderzucker": "zum Bestäuben",
              "Zubereitung 1": "Ofen auf 160 Grad vorheizen.",
              "Zubereitung 2": "Mandeln grob hacken, mit Mehl, Orangeat, Sultaninen, Lebkuchengewürz, Zimt, Muskat und Salz in einer Schüssel mischen.",
              "Zubereitung 3": "Schokolade fein hacken, mit dem Honig in eine dünnwandige Schüssel geben, über das nur leicht siedende Wasserbad hängen, sie darf das Wasser nicht berühren. Schokolade schmelzen, glatt rühren.",
              "Zubereitung 4": "Rahm und Schokolade zur Mandelmischung geben, mischen, in die vorbereitete Form geben. Masse mit einem nassen Löffelrücken glatt streichen.",
              "Zubereitung 5": "Backen: ca. 30 Min. in der Mitte des Ofens. Herausnehmen, etwas abkühlen, Formenrand entfernen. Panforte mit dem Backpapier auf das Gitter schieben, auskühlen, mit Puderzucker bestäuben."
              }

Matcha_Kokos_Schnitten_L = {"Butterkekse": 180,
                            "Kondensmilch": 300,
                            "Butter": 80,
                            "Kokosraspeln": 100,
                            "Zeste von Anzahl Zitronen": 1,
                            "Saft von Anzahl Zitronen": 0.5,
                            "Matchapulver in TL": 2,
                            "Puderzucker": 200,
                            "Zubereitung 1": "Butterkekse grob zerkleinern. Mit Kokosraspeln und Zitronenabrieb mischen.",
                            "Zubereitung 2": "In einem kleinen Topf Kondensmilch und Butter erhitzen, bis die Butter geschmolzen ist. Zitronensaft dazugeben und gut umrühren.",
                            "Zubereitung 3": "Die Kondensmilch-Butter-Masse mit der Butterkeksmischung gut verrühren.",
                            "Zubereitung 4": "In eine mit Backpapier ausgelegte Form geben, flach andrücken und bis zur Fertigstellung des Zuckergusses in den Kühlschrank stellen.",
                            "Zubereitung 5": "Puderzucker und Matcha gut mischen. Heißes Wasser peu à peu dazu geben und zu einer glatten, nicht zu flüssigen Masse rühren. Auf die Keksmasse dünn aufstreichen und im Kühlschrank aushärten lassen (ca. 1 Stunde).",
                            "Zubereitung 6": "In Stücke schneiden und mit Kokosraspeln garnieren. Passt gut zu schwarzem oder grünem Tee."
}

Goma_Ae_L = {"Blattspinat": 500,
             "Sesamsamen in EL": 2,
             "Sojasauce in EL": 2,
             "Mirin in EL": 1,
             "Zucker in TL": 1,
             "Salz": "eine Prise",
             "Zubereitung 1": "Spinat waschen und in kochendem Wasser blanchieren, bis er weich ist. Dann sofort in Eiswasser abkühlen und gut abtropfen lassen.",
             "Zubereitung 2": "Die Sesamsamen in einer Pfanne ohne Öl bei mittlerer Hitze rösten, bis sie duften. Dann abkühlen lassen und grob mahlen.",
             "Zubereitung 3": "Sojasauce, Mirin, Zucker und Salz in einer Schüssel vermischen, bis sich der Zucker aufgelöst hat.",
             "Zubereitung 4": "Den Spinat ausdrücken, um überschüssige Feuchtigkeit zu entfernen, und grob hacken.",
             "Zubereitung 5": "Den gehackten Spinat und die gemahlenen Sesamsamen in die Sojasauce-Mischung geben und gut vermengen.",
             "Zubereitung 6": "Kalt oder bei Raumtemperatur servieren."
}

Agedashi_Nasu_L= {"Auberginen": 2,
                  "Maisstärke in EL": 4,
                  "Pflanzenöl zum Frittieren": "nach Bedarf",
                  "Dashi in ml": 240,
                  "Sojasauce in EL": 2,
                  "Mirin in EL": 2,
                  "Zucker in TL": 1,
                  "Frühlingszwiebeln zum Garnieren": "nach Geschmack",
                  "Ingwer zum Garnieren": "nach Geschmack",
                  "Rettich zum Garnieren": "nach Geschmack",
                  "Bonitoflocken zum Garnieren": "nach Geschmack",
                  "Zubereitung 1": "Auberginen waschen und in Scheiben schneiden. Mit Küchenpapier trocken tupfen.",
                  "Zubereitung 2": "Die Auberginenscheiben leicht in Maisstärke wenden, um sie zu panieren.",
                  "Zubereitung 3": "In einem Topf Pflanzenöl erhitzen und die panierten Auberginenscheiben goldbraun frittieren.",
                  "Zubereitung 4": "Dashi, Sojasauce, Mirin und Zucker in einem anderen Topf mischen und zum Kochen bringen.",
                  "Zubereitung 5": "Die frittierten Auberginenscheiben auf einem Teller anrichten und mit der heißen Dashi-Sojasauce übergießen.",
                  "Zubereitung 6": "Mit gehackten Frühlingszwiebeln und geriebenem Ingwer garnieren. Nach Geschmack auch dünn geschnittenen Rettich und Bonitoflocken darüberstreuen.",
                  "Zubereitung 7": "Heiß servieren und genießen!"
}


Miso_Ramen_Nudelsuppe_L= {"Ramennudeln": 400,
                          "Miso-Paste in Esslöffel": 4,
                          "Rinderbrühe in Liter": 1,
                          "Sojasauce in Esslöffel": 3,
                          "Sesamöl in Esslöffel": 1,
                          "Ingwer in Teelöffel": 1,
                          "Knoblauch in Zehen": 2,
                          "Frühlingszwiebeln in Stück": 4,
                          "Eier in Stück": 4,
                          "Gekochter Mais Anzahl Dosen": 1,
                          "Gekochte Shiitake-Pilze in Gramm": 200,
                          "Gehackter Koriander": "nach Geschmack",
                          "Gehackter Lauch": "nach Geschmack",
                          "Gehacktes Nori-Algenblatt zum Garnieren": "nach Bedarf",
                          "Zubereitung 1": "Rinderbrühe in einem Topf zum Kochen bringen.",
                          "Zubereitung 2": "Sojasauce, Sesamöl, Ingwer und Knoblauch hinzufügen und köcheln lassen.",
                          "Zubereitung 3": "Währenddessen Ramen-Nudeln nach Anleitung auf der Verpackung kochen und abtropfen lassen.",
                          "Zubereitung 4": "Eier pochieren oder als hart gekochte Eier vorbereiten.",
                          "Zubereitung 5": "Gekochten Mais und Shiitake-Pilze hinzufügen und weitere 5 Minuten köcheln lassen.",
                          "Zubereitung 6": "Die Miso-Paste in die Brühe einrühren und kurz köcheln lassen, bis sie vollständig aufgelöst ist.",
                          "Zubereitung 7": "Die Suppe in Schüsseln portionieren und mit den vorbereiteten Zutaten garnieren, wie Frühlingszwiebeln, Koriander, Lauch und Nori-Algenblättern."
}

Moussaka_L ={"Auberginen in Scheiben": 3,
             "Kartoffeln in Scheiben": 3,
             "Hackfleisch": 500,
             "Zwiebeln in Stück": 2,
             "Knoblauch Anzahl Zehen": 3,
             "Tomaten in Stück": 4,
             "Tomatenmark in Esslöffel": 2,
             "Rotwein in dl": 1,
             "Olivenöl in Esslöffel": 4,
             "Mehl in Esslöffel": 3,
             "Milch in Liter": 1,
             "Eier in Stück": 2,
             "Parmesan": 100,
             "Salz und Pfeffer": "nach Geschmack",
             "Zubereitung 1": "Auberginenscheiben salzen und Wasser ziehen lassen.",
             "Zubereitung 2": "Kartoffeln schälen und in Scheiben schneiden.",
             "Zubereitung 3": "Hackfleisch, Zwiebeln und Knoblauch in Olivenöl anbraten.",
             "Zubereitung 4": "Tomaten, Tomatenmark und Rotwein hinzufügen, würzen und köcheln lassen.",
             "Zubereitung 5": "Für die Bechamelsauce: Mehl in Olivenöl anschwitzen, Milch dazugeben und aufkochen.",
             "Zubereitung 6": "Eier und geriebenen Parmesan unter die Bechamelsauce mischen.",
             "Zubereitung 7": "Eine Schicht Kartoffeln in eine Auflaufform legen, dann eine Schicht Auberginen darauf verteilen.",
             "Zubereitung 8": "Die Hackfleischsoße über die Auberginenschicht gießen.",
             "Zubereitung 9": "Den Rest der Kartoffel- und Auberginenscheiben in Schichten darauf verteilen.",
             "Zubereitung 10": "Die Bechamelsauce gleichmäßig über die oberste Schicht gießen.",
             "Zubereitung 11": "Die Moussaka bei 180°C im vorgeheizten Backofen etwa 45 Minuten backen, bis sie goldbraun ist.",
             "Zubereitung 12": "Aus dem Ofen nehmen und vor dem Servieren kurz abkühlen lassen."}

Tzatziki_L = {"Gurken in Stück": 1,
              "Griechenjoghurt": 200,
              "Knoblauchzehe": 1,
              "Olivenöl in Esslöffel": 2,
              "Zitronensaft in Esslöffel": 1,
              "Gehackte frische Minze in Esslöffel": 2,
              "Salz und Pfeffer": "nach Geschmack",
              "Zubereitung 1": "Die Gurke reiben und in einem Sieb abtropfen lassen.",
              "Zubereitung 2": "Knoblauchzehe fein hacken oder pressen.",
              "Zubereitung 3": "Den abgetropften Joghurt in eine Schüssel geben und die Gurke, den Knoblauch und die gehackte Minze hinzufügen.",
              "Zubereitung 4": "Olivenöl und Zitronensaft hinzufügen und gut umrühren.",
              "Zubereitung 5": "Mit Salz und Pfeffer abschmecken.",
              "Zubereitung 6": "Das Tzatziki für mindestens eine Stunde im Kühlschrank ziehen lassen, damit sich die Aromen verbinden können.",
              "Zubereitung 7": "Vor dem Servieren nochmals abschmecken und nach Bedarf mit etwas Olivenöl und frischer Minze garnieren."
}

Baklava_L= {"Walnüsse ": 200,
            "Mandel": 200,
            "Blätterteig": 1,
            "Butter": 150,
            "Zucker": 200,
            "Wasser in ml": 200,
            "Honig": 150,
            "Zimt in TL": 1,
            "Nelkenpulver in Prise": 1,
            "Zubereitung 1": "Walnüsse und Mandeln grob hacken.",
            "Zubereitung 2": "Den Blätterteig in eine Backform legen und mit Butter bestreichen.",
            "Zubereitung 3": "Die gehackten Nüsse auf den Blätterteig legen und leicht andrücken.",
            "Zubereitung 4": "Den Blätterteig mit einem scharfen Messer in Rhomben oder Quadrate schneiden.",
            "Zubereitung 5": "Im vorgeheizten Backofen bei 180°C etwa 25 Minuten goldbraun backen.",
            "Zubereitung 6": "In einem Topf Wasser, Zucker, Honig, Zimt und Nelkenpulver aufkochen lassen und zu einem Sirup einkochen.",
            "Zubereitung 7": "Den heißen Sirup über das heiße Baklava gießen und abkühlen lassen.",
            "Zubereitung 8": "Vor dem Servieren das Baklava in die einzelnen Stücke schneiden und servieren." 
}

Gurkensalat_L = {"Gurken in Stück": 2,
                 "Saure Sahne in EL": 4,
                 "Essig in EL": 2,
                 "Zucker in TL": 1,
                 "Salz und Pfeffer": "nach Geschmack",
                 "Dill in EL": 2,
                 "Zubereitung 1": "Die Gurken waschen, schälen und in dünne Scheiben schneiden oder hobeln.",
                 "Zubereitung 2": "In einer Schüssel die saure Sahne, den Essig, den Zucker, Salz und Pfeffer vermischen.",
                 "Zubereitung 3": "Die Gurkenscheiben dazugeben und alles gut vermengen.",
                 "Zubereitung 4": "Den Dill fein hacken und über den Gurkensalat streuen.",
                 "Zubereitung 5": "Den Gurkensalat für mindestens 30 Minuten im Kühlschrank ziehen lassen, damit sich die Aromen entfalten können.",
                 "Zubereitung 6": "Vor dem Servieren nochmals abschmecken und nach Bedarf mit frischem Dill garnieren."
  } 

Rinderrouladen_L ={"Rinderrouladen in Stück": 4,
                   "Senf in EL": 4,
                   "Speck in Scheiben": 8,
                   "Zwiebeln in Stück": 2,
                   "Gewürzgurken in Stück": 4,
                   "Mehl in EL": 2,
                     "Butter": 50,
                     "Rinderbrühe in ml": 500,
                     "Rotwein in ml": 250,
                     "Rotkohl": 800,
                     "Zucker in EL": 2,
                     "Apfelessig in EL": 2,
                     "Kartoffeln": 800,
                     "Butter(für Kartoffelklöße)": 50,
                     "Semmelbrösel": 100,
                     "Eier in Stück": 1,
                     "Salz und Pfeffer": "nach Geschmack",
                     "Muskatnuss in Prise": 1,
                     "Zubereitung 1": "Die Rinderrouladen abwaschen und trocken tupfen. Mit Senf bestreichen und mit Salz und Pfeffer würzen.",
                     "Zubereitung 2": "Jede Rinderroulade mit einer Scheibe Speck, Zwiebelringen und Gewürzgurken belegen und fest aufrollen. Mit Küchengarn fixieren.",
                     "Zubereitung 3": "In einem Bräter die Butter erhitzen und die Rinderrouladen von allen Seiten scharf anbraten.",
                     "Zubereitung 4": "Das Mehl darüber streuen und kurz anschwitzen lassen.",
                     "Zubereitung 5": "Mit Rinderbrühe und Rotwein ablöschen und etwa 2 Stunden schmoren lassen, bis das Fleisch zart ist.",
                     "Zubereitung 6": "In einem separaten Topf den Rotkohl mit Zucker, Apfelessig, Salz und Pfeffer zum Kochen bringen und etwa 1 Stunde köcheln lassen.",
                     "Zubereitung 7": "Die Kartoffeln schälen, kochen und zu Klößen formen. In kochendem Salzwasser garen.",
                     "Zubereitung 8": "Die Kartoffelklöße in den Semmelbröseln wälzen und in heißer Butter goldbraun braten.",
                     "Zubereitung 9": "Die Rinderrouladen aus dem Bräter nehmen und die Sauce nach Bedarf mit etwas Wasser verdünnen und abschmecken.",
                     "Zubereitung 10": "Die Rinderrouladen mit Rotkohl und Kartoffelklößen servieren und mit der Sauce übergießen." 
}

Apfelstrudel_L ={ "Äpfel in Stück": 4,
                 "Zucker in EL": 4,
                 "Rosinen": 100,
                 "Zimt in TL": 2,
                 "Zitronensaft in EL": 2,
                 "Butter": 50,
                 "Strudelteigblätter": 6,
                 "Semmelbrösel": 50,
                 "Puderzucker zum Bestäuben": "nach Bedarf",
                 "Vanillesauce": "nach Bedarf",
                 "Zubereitung 1": "Die Äpfel schälen, entkernen und in dünne Scheiben schneiden.",
                 "Zubereitung 2": "Die Apfelscheiben mit Zucker, Rosinen, Zimt und Zitronensaft vermengen.",
                 "Zubereitung 3": "Den Strudelteig ausbreiten und mit geschmolzener Butter bestreichen.", 
                 "Zubereitung 4": "Die Semmelbrösel auf dem Teig verteilen.",
                 "Zubereitung 5": "Die Apfelmischung auf dem Teig gleichmäßig verteilen, dabei einen Rand frei lassen.",
                 "Zubereitung 6": "Den Teig seitlich einschlagen und vorsichtig aufrollen, dabei die Enden gut verschließen.",
                 "Zubereitung 7": "Den Apfelstrudel auf ein mit Backpapier ausgelegtes Backblech legen und mit Butter bestreichen.",
                 "Zubereitung 8": "Im vorgeheizten Backofen bei 180°C etwa 30-40 Minuten goldbraun backen.",
                 "Zubereitung 9": "Den Apfelstrudel aus dem Ofen nehmen und mit Puderzucker bestäuben.",
                 "Zubereitung 10": "Den Apfelstrudel warm mit Vanillesauce servieren."
  }

Pad_Thai_L = { "Reisnudeln": 200,
              "Garnelen": 200,
              "Tofu": 150,
              "Eier in Stück": 2,
              "Knoblauch in Zehen": 3,
              "Frühlingszwiebeln in Stück": 4,
              "Sojasauce in EL": 3,
              "Fischsauce in EL": 2,
              "Tamarindenpaste in EL": 2,
              "Chiliflocken in TL": 1,
              "Erdnüsse": 50,
              "Limetten in Stück": 2,
              "Rapsöl in EL": 2,
              "Zubereitung 1": "Reisnudeln nach Packungsanleitung kochen und abtropfen lassen.",
              "Zubereitung 2": "Knoblauch fein hacken, Frühlingszwiebeln in kleine Stücke schneiden.",
              "Zubereitung 3": "Tofu in Würfel schneiden und in einer Pfanne mit etwas Öl goldbraun anbraten.",
              "Zubereitung 4": "Garnelen und Knoblauch hinzufügen und kurz anbraten.",
              "Zubereitung 5": "Die Eier aufschlagen und in die Pfanne geben. Gut verrühren, bis sie gestockt sind.",
              "Zubereitung 6": "Reisnudeln, Sojasauce, Fischsauce, Tamarindenpaste und Chiliflocken dazugeben. Alles gut vermengen.",
              "Zubereitung 7": "Mit Erdnüssen und Frühlingszwiebeln garnieren. Mit Limettenspalten servieren."
  }

Tom_Kha_Gai_L= {"Hähnchenbrust": 400,
                "Kokosmilch in ml": 400,
                "Hühnerbrühe in ml": 500,
                "Galangal in Scheiben": 4,
                "Zitronengras in Stücke": 2,
                "Kaffir-Limettenblätter": 4,
                "Chilis in Stücke": 2,
                "Pilze": 200,
                "Koriander zum Garnieren": "nach Bedarf",
                "Limetten zum Servieren": "nach Bedarf",
                "Fischsauce in EL": 2,
                "Zucker in TL": 1,
                "Zubereitung 1": "Hähnchenbrust in dünne Scheiben schneiden.",
                "Zubereitung 2": "Kokosmilch und Hühnerbrühe in einem Topf zum Kochen bringen.",
                "Zubereitung 3": "Galangal, Zitronengras, Kaffir-Limettenblätter und Chilis hinzufügen.",
                "Zubereitung 4": "Hähnchenbrust und Pilze dazugeben und köcheln lassen, bis das Hähnchen gar ist.",
                "Zubereitung 5": "Mit Fischsauce und Zucker abschmecken.",
                "Zubereitung 6": "Mit frischem Koriander garnieren und mit Limettenspalten servieren."
}

Som_Tam_L = {"Papaya": 300,
             "Karotten": 100,
             "Tomaten in Stück": 2,
             "Grüne Bohnen in Stück": 50,
             "Knoblauch Anzahl Zehen": 2,
             "Chilis in Stück": 2,
             "Limetten in Stück": 2,
             "Fischsauce in EL": 2,
             "Zucker in EL": 1,
             "Gehackte Erdnüsse zum Garnieren": "nach Bedarf",
             "Zubereitung 1": "Grüne Papaya und Karotten schälen und in dünne Streifen hobeln oder schneiden.",
             "Zubereitung 2": "Knoblauch und Chilis fein hacken.",
             "Zubereitung 3": "Grüne Bohnen in kochendem Wasser kurz blanchieren, abtropfen lassen und halbieren.",
             "Zubereitung 4": "In einer Schüssel die gehobelte Papaya, Karotten, Tomaten, grüne Bohnen, Knoblauch und Chilis vermischen.",
             "Zubereitung 5": "Fischsauce, Zucker und Limettensaft hinzufügen und gut vermengen.",
             "Zubereitung 6": "Mit gehackten Erdnüssen bestreuen und servieren."
  }

Tom_Yum_L ={"Hühnerbrühe in ml": 500,
            "Zitronengras in Stück": 2,
            "Galangal in Scheiben": 3,
            "Kaffir-Limettenblätter": 4,
            "Chilis in Stücken": 2,
            "Champignons": 100,
            "Koriander zum Garnieren": "nach Bedarf",
            "Limetten zum Servieren": "nach Bedarf",
            "Fischsauce in EL": 2,
            "Zucker in TL": 1,
            "Zubereitung 1": "Hühnerbrühe in einem Topf zum Kochen bringen.",
            "Zubereitung 2": "Zitronengras, Galangal, Kaffir-Limettenblätter und Chilis hinzufügen und köcheln lassen, bis die Aromen freigesetzt werden.",
            "Zubereitung 3": "Champignons hinzufügen und weiter köcheln lassen, bis sie gar sind.",
            "Zubereitung 4": "Mit Fischsauce, Zucker und Limettensaft abschmecken.",
            "Zubereitung 5": "Mit frischem Koriander garnieren und mit Limettenspalten servieren." 
}

Mango_Reis_L = {"Klebriger Reis Anzahl Tassen": 1,
                "Kokosmilch in ml": 400,
                "Zucker in EL": 3,
                "Salz in TL": 0.5,
                "Reife Mango in Scheiben": "nach Bedarf",
                "Sesamsamen zum Garnieren": "nach Bedarf",
                "Zubereitung 1": "Den klebrigen Reis gründlich waschen und mindestens 4 Stunden oder über Nacht in Wasser einweichen lassen.",
                "Zubereitung 2": "Den Reis abgießen und in einem Dampfgarer oder Reiskocher weich kochen.",
                "Zubereitung 3": "In einem Topf die Kokosmilch, Zucker und Salz erwärmen und gut umrühren, bis sich der Zucker aufgelöst hat.",
                "Zubereitung 4": "Den gekochten klebrigen Reis hinzufügen und gründlich mit der Kokosmilchmischung vermengen. Bei Bedarf mehr Zucker hinzufügen.",
                "Zubereitung 5": "Die Mango in Scheiben schneiden und mit dem klebrigen Reis servieren. Mit Sesamsamen garnieren und warm oder gekühlt genießen."
  } 

Banana_Roti_L= { "Mehl": 120,
                "Wasser in ml": 100,
                "Salz in TL": 0.5,
                "Banane": 2,
                "Zucker in EL": 2,
                "Öl zum Braten": "nach Bedarf",
                "Kondensmilch zum Servieren": "nach Bedarf",
                "Zubereitung 1": "In einer Schüssel Mehl, Wasser und Salz zu einem glatten Teig kneten. Den Teig zu einer Kugel formen, mit einem Tuch abdecken und 30 Minuten ruhen lassen.",
                "Zubereitung 2": "Den Teig in kleine Portionen teilen und jede Portion zu einem dünnen Kreis ausrollen.",
                "Zubereitung 3": "Die Bananen schälen und längs halbieren.",
                "Zubereitung 4": "Etwas Öl in einer Pfanne erhitzen. Den Teigkreis in die Pfanne geben und auf beiden Seiten goldbraun braten.",
                "Zubereitung 5": "Eine halbe Banane auf die Hälfte des gebratenen Teigs legen, mit etwas Zucker bestreuen und den Teig über die Banane klappen. Weitere 1-2 Minuten braten, bis der Roti goldbraun ist.",
                "Zubereitung 6": "Den Banana Roti aus der Pfanne nehmen, in Stücke schneiden und mit Kondensmilch beträufeln. Warm servieren und genießen."
}

Spaghetti_L= { "Spaghetti": 500,
                "Speck- oder Schinkenwürfel": 100,
                "Knoblauch in Stück": 2,
                "Eier in Stück": 3,
                "Rahm in dl": 1,
                "Sprinz oder Parmino": 75,
                "Pfeffer": "nach Bedarf",
                "wenig Salz": "nach Bedarf",
                "Zubereitung 1": "paghetti in reichlich Salzwasser al dente kochen.",
                "Zubereitung 2": "Speck in der Bratpfanne knusprig braten, Pfanne vom Herd nehmen. Knoblauch dazu pressen, umrühren. Pfanne etwas abkühlen lassen, damit die Eimasse nicht gerinnt beim Mischen mit den Spaghetti.",
                "Zubereitung 3": "Eier, Rahm, Pfeffer und Salz in einer Schüssel kräftig verrühren. Käse daruntermischen. Eimasse in die abgekühlte Bratpfanne zu Speck und Knobli giessen. Spaghetti abgiessen und gut abtropfen lassen, zur Eimasse geben.",
                "Zubereitung 4": "Vorsichtig mischen.",
                "Zubereitung 5": "Spaghetti auf vorgewärmten Tellern verteilen und nach Belieben Käse darüber reiben." 
}

Tortilla_L = {"Vollkorn-Tortillas in Stück": 6,
                "Teigwaren": 250,
                "Speckwürfeli": 160,
                "Reibkäse": 250,
                "Vollrahm in dl": 1,
                "Pfeffer": "nach Bedarf",
                "wenig Salz": "nach Bedarf",
                "Muskatnuss": "nach Bedarf",
                "Zubereitung 1": "Kartoffeln und Teigwaren (ca. 7 -10 Minutend kochend)zusammen in reichlich Salzwasser garen. Abgiessen und abtropfen lassen. Lagenweise mit dem Käse zurück in die heisse Pfanne oder in eine vorgewärmte Form geben.",
                "Zubereitung 2": "Rahm würzen und über die Teigwaren giessen."
}



Älplermagronen_L = {"festkochende Kartoffeln": 600,
                "Frischkäse oder Crème fraîche": 150,
                "Speckwürfeli": 160,
                "Eier in Stück": 3,
                "Zwiebel Hälfte": 1,
                "Salz prisen": 1,
                "Pfeffer prisen": 1,
                "Zubereitung 1": "Ofen auf 190°C Heissluft vorheizen (Ober-/Unterhitze 210°C).",
                "Zubereitung 2": "Je 2 Tortillas auf die vorbereiteten Bleche legen, mit je 2 EL Frischkäse/Crème fraîche bestreichen. Speckwürfeli und Zwiebel darauf verteilen, mit Salz und Pfeffer würzen.",
                "Zubereitung 3": "Im vorgeheizten Ofen ca. 10 Minuten backen, bis die Tortillas am Rand zu bräunen beginnen. Je nach Ofen nach der Hälfte der Zeit Bleche tauschen.",
                "Zubereitung 4": "Herausnehmen, Rüebli grob geraffelt und Schnittlauch darauf verteilen, heiss servieren.",
}


Flammkuchen_L = {"Mehl": 220,
                "Frischkäse oder Crème fraîche": 150,
                "Salz prisen": 1,
                "Zucker in Msp.": 1,
                "Hefe": 10,
                "Wasser in dl": 1.25,
                "Butter, flüssig in EL": 3,
                "Crème fraîche": 200,
                "Zwibel in Stück": 3,
                "Speckwürfeli": 150,
                "Pfeffer": "nach Bedarf",
                "wenig Salz": "nach Bedarf",
                "Muskatnuss": "nach Bedarf",
                "Zubereitung 1": "Teig: Mehl, Salz und Zucker mischen, eine Mulde formen. Hefe in wenig Wasser auflösen. Mit restlichem Wasser und Butter in die Mulde giessen.",
                "Zubereitung 2": "Alles zu einem geschmeidigen Teig kneten. Zugedeckt unter Klarsichtfolie bei Raumtemperatur aufs Doppelte aufgehen lassen.",
                "Zubereitung 3": "Backofen auf 220°C Heissluft/Umluft (idealerweise mit zusätzlicher Unterhitze) vorheizen (Ober-/Unterhitze 240°C).",
                "Zubereitung 4": "Teig auf wenig Mehl ca. 2 mm dick auswallen (28-35 cm Ø). Auf das mit Backpapier belegte Blech legen, mit einer Gabel mehrmals dicht einstechen.",
                "Zubereitung 5": "Belag: Teig mit Crème fraîche bestreichen, dabei rundum 1 cm Rand freilassen, Zwiebeln und Speck darauf verteilen. Würzen.",
                "Zubereitung 6": "Flammkuchen auf der untersten Rille des vorheizten Ofens 13-16 Minuten backen.",
                "Zubereitung 7": "Frischkäse darüberstreuen, garnieren."
}

Gefüllte_Zucchini_L = {"Rindshackfleisch": 500,
                "Ei verquirlt": 1,
                "gelbe Peperoniwürfel in Stück": 1/2,
                "Knoblauchzehe in Stück": 1,
                "Halbfettquark in EL": 3,
                "Oregano in EL": 1,
                "Peterli in EL": 1,
                "Salz in TL": 1,
                "Pfeffer": "nach Bedarf",
                "Zucchini in Stück": 4,
                "Gemüsebouillon in dl": 2,
                "Feta zerbröckelt": 100,
                "Zubereitung 1": "Alle Zutaten gut mischen, würzen.",
                "Zubereitung 2": "Zucchini rundum mit Bratbutter bestreichen, salzen, mit der Schnittfläche nach oben in die ausgebutterte Form legen. Fleisch-Masse darauf verteilen, andrücken. Bouillon in die Form giessen.",
                "Zubereitung 3": "Zucchini rundum mit Bratbutter bestreichen, salzen, mit der Schnittfläche nach oben in die ausgebutterte Form legen. Fleisch-Masse darauf verteilen, andrücken. Bouillon in die Form giessen.",
                "Zubereitung 4": "Herausnehmen, Rüebli grob geraffelt und Schnittlauch darauf verteilen, heiss servieren.",
}

Gyoza_L = {"Mehl": 250,
                "Speisestärke in EL": 1.5,
                "Salz in TL": 1/4,
                "	Wasser, heiss in dl": 1.5,
                "Pilze, klein gehackt": 200,
                "Bundzwiebel in Stück": 1,
                "Knoblauchzehe in Stück": 1,
                "Frischkäse": 100,
                "Paniermehl in EL": 3,
                "Sojasauce in TL": 2,
                "Ingwer in TL": 1/2,
                "Pfeffer": "nach Bedarf",
                "Sojasauce in EL": 3,
                "Zitronensaft in EL": 1,
                "Chilli": "nach Bedarf",
                "wenig Bratcrème": "zum Anbraten",
                "Wasser in dl": 0.5,
                "Zubereitung 1": "Teig: Mehl, Stärke und Salz in eine Schüssel geben, mischen. Wasser dazugiessen, zu einem geschmeidigen Teig kneten. Mit einem feuchten Tuch decken. Mindestens 15 Minuten bei Raumtemperatur ruhen lassen.",
                "Zubereitung 2": "Füllung: Alle Zutaten (Pilze, Bundzwibeln, Koblauch, Frischkäse, Paniermehl, Sojasauce und Ingwer) mischen, abschmecken.",
                "Zubereitung 3": "Füllen: Rondelle in die Hand nehmen, Rand mit wenig Wasser bestreichen. 1 TL Füllung in die Mitte geben. Zusammenklappen, Ränder gut zusammendrücken. Für eine schöne Optik den Teigrand mehrmals zusammenstossen, sodass ein wellenförmiges Muster entsteht.",
                "Zubereitung 4": "Sauce: Alle Zutaten (Sojasacue, Zitroensaft und Chilli) mischen.",
                "Zubereitung 5": "Gyoza in die Bratpfanne setzen, bei mittlerer Hitze in Bratcrème 1-2 Minuten braten, ohne sie zu wenden. Wasser beigeben, zugedeckt 5-7 Minuten dämpfen. Deckel entfernen, das Wasser verdampfen lassen.",
                "Zubereitung 6": "Anrichten, mit Bundzwiebelkraut bestreuen. Gyoza in die Sauce tunken, geniessen."
}

Kochbuch = {"Nudeln": Nudeln_L, 
            "Kuchen" : Kuchen_L,
            "Parmigiana": Parmigiana_L,
            "Lasagne": Lasagne_L,
            "Bruschetta": Bruschetta_L,
            "Panna cotta": Panna_cotta_L,
            "Panforte": Panforte_L,
            "Matcha-Kokos-Schnitten": Matcha_Kokos_Schnitten_L,
            "Goma Ae": Goma_Ae_L,
            "Agedashi Nasu": Agedashi_Nasu_L,
            "Miso-Ramen-Nudelsuppe": Miso_Ramen_Nudelsuppe_L,
            "Moussaka": Moussaka_L,
            "Tzatziki": Tzatziki_L,
            "Baklava": Baklava_L,
            "Gurkensalat": Gurkensalat_L,
            "Rinderrouladen mit Rotkohl und Kartoffelklößen": Rinderrouladen_L,
            "Apfelstrudel mit Vanillesauce": Apfelstrudel_L,
            "Pad Thai": Pad_Thai_L,
            "Tom Kha Gai": Tom_Kha_Gai_L,
            "Som Tam": Som_Tam_L,
            "Tom Yum Suppe": Tom_Yum_L,
            "Mango mit klebrigem Reis": Mango_Reis_L,
            "Banana Roti": Banana_Roti_L,
            "Spaghetti Carbonara": Spaghetti_L,
            "Tortilla-Flammkuchen": Tortilla_L,
            "Älplermagronen": Älplermagronen_L,
            "Flammkuchen": Flammkuchen_L,
            "Gefüllte Zucchini mit Hackfleisch": Gefüllte_Zucchini_L,
            "Gyoza mit Pilzfüllung": Gyoza_L

}

#Speiseliste nicht erweitern
Speise_L = ["Vorspeise", "Hauptspeise", "Nachspeise"]




